version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    # environment:
    #   - DB_CONNECTION=sqlite
    #   - DB_DATABASE=/var/www/html/database/database.sqlite
